### ISSUE TITLE
Uncaught exception 'Exception' read_bytes(): Unexpected end of stream

### ISSUE THREAD

**Issue by Gandaflux** [NicklasWallgren/PokemonGoAPI-PHP#91] opened 2016-08-11 14:13 UTC
After update got little bug ;-)
Already deleted all files and clone/install again, didn't help :/ 

```
Fatal error: Uncaught exception 'Exception' with message 'read_bytes(): Unexpected end of stream' in /home/gnat/www/oku.pl/PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php:364 
Stack trace: 
#0 /home/gnat/www/oku.pl/PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Networking/Envelopes/ResponseEnvelope.php(95): Protobuf::read_bytes(Resource id #129, 21788, 9223372036854775795) 
#1 /home/gnat/www/oku.pl/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php(257): POGOProtos\Networking\Envelopes\ResponseEnvelope->read(Resource id #129) 
#2 /home/gnat/www/oku.pl/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php(242): NicklasW\PkmGoApi\Handlers\RequestHandler->unmarshall(Object(GuzzleHttp\Psr7\Response)) 
#3 /home/gnat/www/oku.pl/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php(118): NicklasW\PkmGoApi\Handlers\RequestHandler->call(Object(POGOProtos\Networking\Envelopes\RequestEnvelope)) 
#4 /home/gnat/www/oku.pl/PokemonGoAPI-PHP/src/Services/Request/InventoryRequestService.php(21): NicklasW\PkmGoApi in /home/gnat/www/oku.pl/PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php on line 364
```

**Comment by NicklasWallgren** [comment] 2016-08-11 14:16
How did you authenticate?

**Comment by paoloalby** [comment] 2016-08-11 14:26
A user just got the same error from my [website](http://www.pogoinformer.com) trying to authenticate with Google Auth Key.
But I can't reproduce the error. If I try, I don't get any error like this, and I can login without any problems.


![schermata 2016-08-11 alle 16 08 49](https://cloud.githubusercontent.com/assets/15869726/17591788/f4bf8e22-5fdf-11e6-9784-ab0d555a244c.png)

**Comment by Gandaflux** [comment] 2016-08-11 14:27
looks like PTC working. Got problem with google user/pass auth.

**Comment by NicklasWallgren** [comment] 2016-08-11 14:30
Do you experience the same problem if you login using auth code?

**Comment by Gandaflux** [comment] 2016-08-11 14:37
yes. with auth token also same error.

**Comment by NicklasWallgren** [comment] 2016-08-11 14:47
Fixed in latest commit.

**Closed by NicklasWallgren** 2016-08-11 14:47 UTC
